name: Documentation Issue
description: Report an issue with the documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the Blood documentation!

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Outdated information
        - Unclear explanation
        - Typo or grammar
        - Broken link
        - Missing example
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the issue? (URL, file path, or section name)
      placeholder: "docs/spec/EFFECTS.md or https://blood-lang.org/docs/..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue.
      placeholder: |
        The documentation says X, but actually Y...
        This section is confusing because...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix this, please share it.
      placeholder: |
        I suggest changing...
        A better explanation would be...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this issue
