name: Feature Request
description: Suggest a new feature or enhancement for Blood
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Language (syntax, semantics)
        - Compiler (bloodc)
        - Runtime (blood-runtime)
        - Standard Library (stdlib)
        - Effect System
        - Type System
        - Tooling (LSP, formatter, etc.)
        - Documentation
        - Build System
        - Package Manager
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        Currently, I have to...
        This is frustrating because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: |
        I would like Blood to...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? What are you doing currently as a workaround?
      placeholder: |
        I've tried...
        Another approach could be...

  - type: textarea
    id: code-example
    attributes:
      label: Example Code
      description: If applicable, show what the feature would look like in practice.
      render: blood
      placeholder: |
        // Before (current behavior)
        fn example() {
            // ...
        }

        // After (with proposed feature)
        fn example() {
            // ...
        }

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use of Blood)
        - High (significantly improves my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this feature require breaking existing code?
      options:
        - "No"
        - "Yes, minor"
        - "Yes, significant"
        - "Unknown"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, links, or references that might help.
      placeholder: |
        Related issues: #123
        Similar feature in other languages: ...
        Research papers: ...

  - type: checkboxes
    id: involvement
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions for this feature
          required: true
        - label: I have read the Blood language specification
          required: false
